#Prod PRI vars

env_prod: true
is_dr: false
profile: "prod"
aws_region: "eu-west-1" 
#Network defaults
cidr_block: "192.168.0.0/16"
private_availability_zones: ["eu-west-1a", "eu-west-1b"]
public_availability_zones: ["eu-west-1a", "eu-west-1b"]
private_cidr_blocks: ["192.168.1.0/24", "192.168.2.0/24"]
public_cidr_blocks: ["192.168.3.0/24", "192.168.4.0/24"]
nat_ami: "ami-0c55b159cbfafe1f0"
nat_instance_type: "t2.micro"

#LT + ASG defaults
asg_cplane_key_name: "cplane"
asg_cplane_min_vcpu_count: "2"
asg_cplane_max_vcpu_count: "4"
asg_cplane_min_memory_mib: "2048"
asg_cplane_max_memory_mib: "4096"

