#Dev DR vars

env_prod: false
is_dr: true
profile: "dev-dr"
aws_region: "eu-west-2" 
#Network defaults
cidr_block: "192.168.0.0/16"
private_availability_zones: ["eu-west-2a", "eu-west-2b"]
public_availability_zones: ["eu-west-2a", "eu-west-2b"]
private_cidr_blocks: ["192.168.1.0/24", "192.168.2.0/24"]
public_cidr_blocks: ["192.168.3.0/24", "192.168.4.0/24"]
nat_instance_type: "t4g.micro"

#LT + ASG defaults
asg-cplane-min-vcpu-count: 2
asg-cplane-max-vcpu-count: 4
asg-cplane-min-memory-mib: 2048
asg-cplane-max-memory-mib: 4096
asg-workers-min-vcpu-count: 2
asg-workers-max-vcpu-count: 4
asg-workers-min-memory-mib: 2048
asg-workers-max-memory-mib: 4096